// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkSDRp_nKX0dLOUAEXu9sycPe1_UAqxk4',
    appId: '1:901366069096:web:4401d1bec66be24e7988dd',
    messagingSenderId: '901366069096',
    projectId: 'trash-manajemen1',
    authDomain: 'trash-manajemen1.firebaseapp.com',
    databaseURL: 'https://trash-manajemen1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trash-manajemen1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARGsCi0kv7YVPHPDuGfRgDN-XJ6MIvbyQ',
    appId: '1:901366069096:android:8b6b11334e5fe2d87988dd',
    messagingSenderId: '901366069096',
    projectId: 'trash-manajemen1',
    databaseURL: 'https://trash-manajemen1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trash-manajemen1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlPA1QugGL61J7SMSSvoME-ivN8KPkstk',
    appId: '1:901366069096:ios:30bd41683ce13d5a7988dd',
    messagingSenderId: '901366069096',
    projectId: 'trash-manajemen1',
    databaseURL: 'https://trash-manajemen1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trash-manajemen1.firebasestorage.app',
    iosBundleId: 'com.example.roleBasedLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlPA1QugGL61J7SMSSvoME-ivN8KPkstk',
    appId: '1:901366069096:ios:30bd41683ce13d5a7988dd',
    messagingSenderId: '901366069096',
    projectId: 'trash-manajemen1',
    databaseURL: 'https://trash-manajemen1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trash-manajemen1.firebasestorage.app',
    iosBundleId: 'com.example.roleBasedLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkSDRp_nKX0dLOUAEXu9sycPe1_UAqxk4',
    appId: '1:901366069096:web:8eb444124db33e377988dd',
    messagingSenderId: '901366069096',
    projectId: 'trash-manajemen1',
    authDomain: 'trash-manajemen1.firebaseapp.com',
    databaseURL: 'https://trash-manajemen1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trash-manajemen1.firebasestorage.app',
  );

}